### ISSUE TITLE
Threading 

### ISSUE THREAD

**Issue by Fastidious** [zusam/zusam#10]
Could it be possible to implement comment threading, so comments can be replied to?

**Comment by nrobinaubertin** [comment]
Yes, the data structure allows it. The only real thing that holds me back on that is the UI.
Comments of comments are generally translated to the right a bit (as on facebook, reddit, hackernews...). When these are text only, it's not a real issue but I would like to maintain full capabilities for comments (uploading files, link previews...) and the reduced spaced due to this shifting will make things not pretty/readable.

So nested comments should be able to use the whole width and be seen as nested comments.
I currently don't have an UI answer for that.

**Comment by Fastidious** [comment]
@nrobinaubertin perhaps for comments with images generating an "in-reply-to" link, instead of shifting to right would be best? Or using that approach for all? I now understand your dilemma.

**Comment by nrobinaubertin** [comment]
Another possibility is doing like slack: add a link to a comment saying that it received replies. The link would open the the comment as a parent message in a new page.  
![slack(1)](https://user-images.githubusercontent.com/5983763/59026240-6cbda680-8845-11e9-9ae4-3bee8b5257b9.png)
It's generic and works for all constraints we have but would not encourage "deep threading" like on reddit. It's more a subthread creation process than a real reply-to.

I don't think that there is a family friendly solution that would work equally on both axis.

**Comment by nrobinaubertin** [comment]
I'm still thinking about this.  
This will also need a complete redesign of the notification system. For now, the groups where there are news are highlighted and same for the messages. This cannot work with replies. So a notification center (with a bell icon in the navbar) needs to be added to see what is going on.

**Comment by devnewton** [comment]
Sample UX implementation that works best than _$n replies_ link or nested comments:

 https://linuxfr.org/board

(move mouse hover HH:mm:ss timestamps to see how it works).

**Comment by Fastidious** [comment]
@devnewton that wouldn't work for me. I find it to be a horrible approach.

**Comment by nrobinaubertin** [comment]
@devnewton: I think that this way of having nested comments is clever but works best in instant communications where the replies are at most 2-3 lines wide.
Another thing to consider is that threading in general is not "family friendly" (I mean not technical people or power users by that). So the solution should be usable (no disorienting) for them.

I'm going to implement threading starting next week. My preference goes toward the slack solution for now.

**Comment by nrobinaubertin** [comment]
Feature added in [`0.4`](https://github.com/zusam/zusam/releases/tag/0.4)
