### ISSUE TITLE
[Feature request] Timeline?

### ISSUE THREAD

**Issue by TheNomad11** [zusam/zusam#15]
Very impressive and simple at the same time! Just one question: Is it possible to implement a timeline where one can follow all posts of a group? Or how one is supposed to do so now? Otherwise it would be a perfect solution also to be used in education, I think!

**Comment by nrobinaubertin** [comment]
Hi, thanks !
I'm not sure to understand your question: Zusam is already organized by groups. You can only see posts of one group at a time and these are chronologically sorted (with the latest post or the latest one that received a comment first).
You can create a new group or select another group to display with the top-right menu:
![group menu screenshot](https://i.imgur.com/zP0mgAI.png)

**Comment by nrobinaubertin** [comment]
Closing for now. Feel free to reopen if you have further questions
