### ISSUE TITLE
Add Download  button

### ISSUE THREAD

**Issue by rmc0** [zusam/zusam#26]
For user want to save picture..

**Comment by nrobinaubertin** [comment]
Yes, good idea. I'll add it.

**Comment by rmc0** [comment]
Another idea : download by picture or by Album

**Comment by nrobinaubertin** [comment]
The download button (when viewing a media) was added as part of the 0.4.4 release.  
Downloading full albums, messages or more will be addressed as part of this issue: https://github.com/zusam/zusam/issues/31
