### ISSUE TITLE
Option to disable video upload

### ISSUE THREAD

**Issue by rmc0** [zusam/zusam#28]
nice work ! easy and fast install ! 

Work well on ARMboard 
- Odroid C2 
- Armbian Buster minimal 

- 154Mo ram
- armbian + zusam install : 1,2 Go

**Comment by nrobinaubertin** [comment]
Thanks !
I'm not sure that video conversion with ffmpeg will work well on a tiny board like this. It could take a long time if you upload a large file to convert.
I was thinking about adding an option to disable video upload: is that something that you would need ?

**Comment by rmc0** [comment]
I agree, disable video can be nice

**Comment by nrobinaubertin** [comment]
Done in `0.4.1`
