### ISSUE TITLE
createdAt attribute in request payload not used

### ISSUE THREAD

**Issue by lmolent** [zusam/zusam#30]
Hi, when trying post new message over API I can see in request payload `createdAt` attribute, but when I try change his value, message is still created with current timestamp. It would be nice have option to change message post date when importing old data from other instances or services (Google Plus Takeout i.e.) :)

author: "44e9954c-c7a7-4895-..."
children: []
**createdAt: 1609330288**
data: {text: "text", title: "title"}
text: "text"
title: "title"
files: []
group: "bb16f4a4-2dc0-43c1-9c7c-..."
lastActivityDate: 1609330288

**Comment by nrobinaubertin** [comment]
Yes, good idea. I'll do it for the 0.4.3 that will be out in january.  
(If there's no createdAt, it will use the server timestamp as it is actually)

**Comment by lmolent** [comment]
Great :+1:

**Comment by nrobinaubertin** [comment]
This was done for the 0.4.3 release
