### ISSUE TITLE
dotenv error

### ISSUE THREAD

**Issue by yearchan** [zusam/zusam#33]
![image](https://user-images.githubusercontent.com/24740865/133034353-7aa610d6-415d-42e1-b9e2-0944ddf90621.png)
i am using the windows system and running the docker.
when i run the command 'docker build -t zusam .' and the above error show.
i think it is some config in correct. can you help to check?
thank you.

**Comment by nrobinaubertin** [comment]
This is because windows doesn't recognize it as a unix symbolic link and transforms it to a simple file with the path to its target.  
I've fixed it with https://github.com/zusam/zusam/commit/d57653afb995b388175b62768fc95ceca2f7cf75, try to pull master and rebuild the container.

**Comment by yearchan** [comment]
it is work now. thank you very much. @nrobinaubertin
