### ISSUE TITLE
Can't rename groups

### ISSUE THREAD

**Issue by geekedtv** [zusam/zusam#39]
First I tried renaming the Zusam group and it wouldn't let me. I figured it was the default group and sometimes you can't rename default groups. Then I tried renaming another group I made and it didnt let me again after pressing "save changes".

**Comment by geekedtv** [comment]
Also, cannot delete or leave groups.

**Comment by nrobinaubertin** [comment]
I confirm that this is a bug. I'll handle it this week

**Comment by nrobinaubertin** [comment]
This is now fixed on the master branch
