### ISSUE TITLE
Latest image for Docker

### ISSUE THREAD

**Issue by mariushosting** [zusam/zusam#40]
Awesome project congrats! Is there any docker zusam/zusam:latest image available I can't find it.

**Comment by nrobinaubertin** [comment]
Hi, thanks !  
No, I didn't publish an image in any registry, you'll have to build it using the Dockerfile in the repository. You can follow [the docker installation guide](https://github.com/zusam/zusam/blob/master/documentation/docker.md) to help you.

**Comment by mariushosting** [comment]
Thank you for the answer! Did you plan to publish an image in the future?

**Comment by nrobinaubertin** [comment]
I didn't really plan it for now.   
Are you using something that doesn't allow you to install it if there isn't an image on a public registry ?

**Comment by mariushosting** [comment]
With a ready-made docker image zusam would become instantly popular :-)

**Comment by nrobinaubertin** [comment]
I'll publish one for the next release

**Comment by mariushosting** [comment]
> I'll publish one for the next release

Awesome! Thank you!

**Comment by geekedtv** [comment]
> > I'll publish one for the next release
> 
> Awesome! Thank you!

Came here to say the same. Good looking out Marius!

**Comment by nrobinaubertin** [comment]
I pushed an image to the dockerhub and added a link into the documentation (https://github.com/zusam/zusam/commit/e06f390c0c531449bcefde33a0d55dc906df8d50)
