### ISSUE TITLE
When uploading video, if you click submit before the upload is complete the post is submitted but the video is lost

### ISSUE THREAD

**Issue by Neriderc** [zusam/zusam#44]
If you:
- Create a new post
- Add a title
- Click to upload a video
- Choose a video that may take a while to upload
- Click the submit button while the video loading bar has not finished
Then the post is submitted and displays in the group, but the video is lost.

I would expect that the submit button should be unavailable while a video is uploading.

**Comment by nrobinaubertin** [comment]
Fixed with 4cfebc8856a8bdfd234f63f52f2a4a63fa3c6253
