### ISSUE TITLE
[bug] (maybe) - the default post is titled "Welcome on Zusam" but this doesn't sound natural in English (to me)

### ISSUE THREAD

**Issue by Neriderc** [zusam/zusam#45]
I know that we normally talk about being "on" the internet, "on" facebook, "on" twitter, but it sounds unnatural to me to say "Welcome on Zusam". 

I speak English as a first language but I know this can still be regional so happy to hear other opinions, but to me it would sound more natural to say "Welcome to Zusam".

**Comment by nrobinaubertin** [comment]
Fixed with https://github.com/zusam/zusam/commit/8d9c87a16470d0b878d032ca89507ad21277481a
