### ISSUE TITLE
Install possible in a subdirectory?

### ISSUE THREAD

**Issue by dragondaddy** [zusam/zusam#57]
Hi there. Just discovered this project and feel it could perfectly suit our needs to keep in touch with our family overseas. I was just wondering if it would be possible to install Zusam in a subdirectory (i.e. mydomain.tld/zusam/) rather than using a full domain/subdomain. If it is indeed possible, do you know what adjusments should be made to the nginx configuration? I'm trying to find out by myself, but I really don't know much about nginx...

Also, note that I'm probably going to try to make a package for YunoHost, so that would also be helpful on that side :)

**Comment by nrobinaubertin** [comment]
Hi,

Yes, it is possible (although I haven't tested it in a long time).  
If you're using the container, there is a `SUBPATH` env that should do the trick.  
If not, then you need to adapt your server settings accordingly to the subpath you want (you can have a look at [this](https://github.com/zusam/zusam/blob/master/container/nginx/nginx-subpath.conf) if you're using nginx). Then, you need to modify the `<base href="/">` tag in `/public/index.html` (the file is initially located in `/app/dist/index.html`). That's it !

It would be great if you could create a package for Yunohost !  
You can use this repo as a starting point if you want: https://github.com/zusam/zusam_ynh (it's a bit old though, I eventually want to archive it).  
Can you notify me if you create a repo in https://github.com/YunoHost-Apps ?

**Comment by dragondaddy** [comment]
I gave it another shot, no luck. I'll just stick it to the full domain install for the moment, and open an issue when the package is in YunoHost-Apps. Should be done by the end of the week. I'll keep you updated.

**Comment by dragondaddy** [comment]
Done! https://github.com/YunoHost-Apps/zusam_ynh

**Comment by nrobinaubertin** [comment]
A fix (https://github.com/zusam/zusam/commit/8c55adef7f0f48898f5d9d965100e6c289619f33) for the subpath feature will be there for the `0.5.4`

**Comment by nrobinaubertin** [comment]
[Documentation added](https://github.com/zusam/zusam/blob/master/documentation/subpath.md) for the `0.5.5` version.
