### ISSUE TITLE
How to set mail server?

### ISSUE THREAD

**Issue by zarevskaya** [zusam/zusam#63]
Hi,
I cannot configure the mail server. I use Zoho Mail and I don't understand:
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="

smtp.zoho.eu
587  TLS

Something like this?

MAILER_DSN="smtp://smtp.zoho.eu:587?encryption=&auth_mode=" ?

Thanks in advance!

**Comment by nrobinaubertin** [comment]
I'm using the symfony mailer component whose documentation is [here](https://symfony.com/doc/current/mailer.html). 

The format should be: `smtp://user:pass@smtp.domain.example:port`.  
So in your case: `smtp://user:pass@smtp.zoho.eu:587`
(where `user` is your zoho username and `pass` your zoho password)

Let me know if that works

**Comment by zarevskaya** [comment]
Hey, thank you, I try soon!

**Comment by nrobinaubertin** [comment]
I'm closing this but feel free to reopen if the issue persists
